#!/bin/bash
# scripts/embed_elfs.sh
#
# Converts user ELF binaries in user/build/*.elf to a Go source file
# (src/user_binaries.go) containing byte-array constants. Each binary
# becomes a var userElf_<name> = [...]byte{...} declaration.
#
# Usage: bash scripts/embed_elfs.sh

set -e

OUTFILE="src/user_binaries.go"

echo "package main" > "$OUTFILE"
echo "" >> "$OUTFILE"
echo "// Code generated by scripts/embed_elfs.sh. DO NOT EDIT." >> "$OUTFILE"
echo "" >> "$OUTFILE"

# Must match maxFileData in src/fs.go:12. Any user ELF larger than
# this cap would be rejected by fsWrite at boot, so abort the
# build early with a clear message instead.
MAX_ELF_SIZE=262144

for elf in user/build/*.elf; do
    if [ ! -f "$elf" ]; then
        echo "No ELF files found in user/build/" >&2
        exit 1
    fi
    name=$(basename "$elf" .elf)
    varname="userElf_${name}"
    size=$(stat -c%s "$elf")
    if [ "$size" -gt "$MAX_ELF_SIZE" ]; then
        echo "embed_elfs: ${name}.elf is ${size} bytes, exceeds maxFileData cap (${MAX_ELF_SIZE})" >&2
        exit 1
    fi
    echo "// ${name}.elf (${size} bytes)" >> "$OUTFILE"
    # Convert binary to Go byte literal. od produces space-separated hex bytes;
    # we format them as 0xNN, with 12 bytes per line.
    echo "var ${varname} = [...]byte{" >> "$OUTFILE"
    od -An -tx1 -v "$elf" | tr -s ' ' '\n' | grep -v '^$' | \
        awk '{printf "0x%s, ", $1; if (NR % 12 == 0) print ""}' >> "$OUTFILE"
    echo "" >> "$OUTFILE"
    echo "}" >> "$OUTFILE"
    echo "" >> "$OUTFILE"
    echo "  embedded: ${name}.elf (${size} bytes)"
done

echo "Generated $OUTFILE"
